distill: false
early_stopping_patience: 5
experiment_name: isic_vit_binary_224
flops_batch: 10
lamda_cos: 1.0
lamda_feat: 1.0
lr: 0.0001
max_epochs: 2
num_classes: 2
output_dir: ISIC2019/isic_vit_binary_224/seed_42
profile_flops: true
seed: 42
task: single_label_classification
top_k: 5
weight_decay: 0.0
