early_stopping_patience: 5
experiment_name: ''
flops_batch: 10
gpus: 1
lr: 0.0001
max_epochs: 2
num_classes: 9
output_dir: ISIC2019/isic_vit_binary_224/seed_42
profile_flops: true
seed: 42
task: single_label_classification
top_k: 5
weight_decay: 0.0
