dropout_rate: 0.1
early_stopping_patience: 5
experiment_name: isic_distillation_vit_binary_224
flops_batch: 10
lamda_cos: 0.3
lamda_feat: 0.7
lr: 0.0003
max_epochs: 30
output_dir: runs/ISIC2017/isic_distillation_vit_binary_224/seed_42
profile_flops: false
seed: 42
task: distillation
teacher:
  embedding_dim: 384
  embeddings_dir: /home/users/ksa828/cool_project/extracted_embeddings_512/ISIC2017/isic_dinov3_emb_512/seed_42/embeddings
top_k: 5
weight_decay: 0.0001
